flaskproject/models.py
# consolidated models module

from .admin.models import *
from .entries.models import *
from .events.models import *
from .users.models import *

flaskproject/entries/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField
from wtforms import validators

class CreateEntryForm(Form):
    # title = TextField('Title', [validators.Length(min=1, max=70)])
    title = StringField('Title', [validators.Length(min=1, max=70)])
    body = TextAreaField('Body', [validators.Length(min=1, max=300)])

class UpdateEntryForm(Form):
    # title = TextField('Title', [validators.Length(min=1, max=70)])
    title = StringField('Title', [validators.Length(min=1, max=70)])
    body = TextAreaField('Body', [validators.Length(min=1, max=300)])

flaskproject/users/forms.py
from flask_wtf import Form
from wtforms import StringField, DateField
from wtforms import validators

from flask_security.forms import RegisterForm

class ExtendedRegisterForm(RegisterForm):
    birth_date = DateField('Birth Date', [validators.DataRequired()], format='%m-%d-%Y')

class EditProfileForm(Form):
    email = StringField('Email Address', [
        validators.DataRequired(),
        validators.Length(min=6, max=30)
    ])
    first_name = StringField('First Name', [validators.Length(min=1, max=70)])
    last_name = StringField('Last Name', [validators.Length(min=1, max=70)])

flaskproject/__init__.py
import os
from flask import Flask, render_template, request
from flask_security import SQLAlchemyUserDatastore, current_user
import logging

from flaskproject.utils import get_instance_folder_path
# from flaskproject.cache import cache

from .core import db, ma, mail, moment, scheduler, security
from .models import User, Role

from .users.forms import ExtendedRegisterForm

from flaskproject.main.views import main
from flaskproject.admin.views import admin
from flaskproject.users.views import user
from flaskproject.events.views import events
from flaskproject.entries.views import entries


def create_app():
    app = Flask(__name__,
                instance_path=get_instance_folder_path(),
                instance_relative_config=True,
                template_folder='templates')

    app.config.from_object('flaskproject.settings')    

    # logging.basicConfig(format=app.config['LOGGING_FORMAT'],filename='logs.log',level=logging.DEBUG)

    # cache.init_app(app)

    db.init_app(app)
    ma.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    security.init_app(app, SQLAlchemyUserDatastore(db, User, Role),
                    register_form=ExtendedRegisterForm)

    # Flask-APScheduler initialize and start.
    scheduler.init_app(app)
    scheduler.start()

    app.jinja_env.add_extension('jinja2.ext.loopcontrols')


    # @app.errorhandler(403)
    # def page_forbidden(error):
    #     app.logger.error('Page forbidden: %s', (request.path, error))
    #     return render_template('errors/403.html'), 403


    # @app.errorhandler(404)
    # def page_not_found(error):
    #     app.logger.error('Page not found: %s', (request.path, error))
    #     return render_template('errors/404.html'), 404


    # @app.errorhandler(500)
    # def internal_server_error(error):
    #     app.logger.error('Server Error: %s', (error))
    #     return render_template('errors/500.html'), 500


    # @app.errorhandler(Exception)
    # def unhandled_exception(error):
    #     app.logger.error('Unhandled Exception: %s', (error))
    #     return render_template('errors/500.html'), 500


    @app.context_processor
    def inject_user():
        return dict(user=current_user)


    @app.route('/')
    def home():
        return render_template('index.html')

    app.register_blueprint(main, url_prefix='/main')
    app.register_blueprint(admin, url_prefix='/admin')
    app.register_blueprint(user, url_prefix='/user')
    app.register_blueprint(events, url_prefix='/events')
    app.register_blueprint(entries, url_prefix='/entries')

    return app

flaskproject/admin/controllers.py
from flask import Blueprint, render_template
from flask import current_app, redirect, request, url_for
from flask_security.decorators import roles_required, current_user
from flaskproject.data.models import db, User
from sqlalchemy import exc


admin = Blueprint('admin', __name__, template_folder='templates')


@admin.route('/')
@roles_required('admin')
def index():
    users = [user for user in User.query.all()]
    return render_template('admin_index.html', users=users)

flaskproject/admin/views.py
from flask import Blueprint, render_template
from flask import current_app, redirect, request, url_for
from flaskproject import db
from flaskproject.users.models import User
from flask_security.decorators import roles_required
from flask_security import login_required, current_user

admin = Blueprint('admin', __name__, template_folder='templates')

@admin.route('/')
@roles_required('admin')
def index():
    users = [user for user in User.query.all()]
    return render_template('admin/admin_index.html', users=users)

flaskproject/entries/views.py
from flask import Blueprint, render_template
from flask import request, redirect, url_for, json, current_app
from ..core import db
from flask_security import login_required, current_user
from datetime import datetime
from .forms import CreateEntryForm, UpdateEntryForm
from .models import Entry
from sqlalchemy import exc

entries = Blueprint('entries', __name__, template_folder='templates')

@entries.route('/')
@login_required
def index():
    user_id = current_user.id
    entries = Entry.query.filter_by(user_id=user_id)

    return render_template('entries/entries.html', entries=entries)

@entries.route('/')
@login_required
def display_entries():
    user_id = current_user.id
    entries = Entry.query.filter_by(user_id=user_id)

    return render_template("entries/entries.html", entries=entries)

@entries.route('/create', methods=['GET', 'POST'])
@login_required
def create_entry():
    form = CreateEntryForm(request.form)

    if request.method == 'POST' and form.validate():
        title = form.title.data
        body = form.body.data
        user_id = current_user.id
        entry = Entry(title, body, user_id)

        try:
            db.session.add(entry)
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)


        return redirect(url_for('entries.display_entries'))

    return render_template("entries/create_entry.html", form=form)

@entries.route('/<entry_id>', methods=['GET', 'POST'])
@login_required
def show(entry_id):
    entry = Entry.query.filter_by(id=entry_id).first_or_404()

    return render_template("entries/show.html", entry=entry)

@entries.route('/edit/<entry_id>', methods=['GET', 'POST'])
@login_required
def update(entry_id):
    entry = Entry.query.filter_by(id=entry_id).first_or_404()

    form = UpdateEntryForm()
    if request.method == "POST" and form.validate_on_submit():
        entry.title = form.title.data
        entry.body = form.body.data

        try:
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

        return redirect(url_for('entries.show', entry_id=entry.id))
    else:
        form.title.data = entry.title
        form.body.data = entry.body

    return render_template("entries/edit.html", entry=entry, form=form)

@entries.route('/delete/<entry_id>', methods=['GET', 'POST'])
@login_required
def delete(entry_id):
    entry = Entry.query.filter_by(id=entry_id).first_or_404()
    user_id = current_user.id
    if user_id == entry.user_id:
        try:
            db.session.delete(entry)
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

        return redirect(url_for('entries.display_entries'))

    return redirect(url_for('entries.display_entries'))

flaskproject/events/views.py
from flask import Blueprint, render_template
from flask import request, redirect, url_for, current_app
from ..core import db
from flask_security import login_required, current_user
from datetime import datetime
from .forms import NewEventForm, UpdateEventForm
from .models import Event
from sqlalchemy import exc

events = Blueprint('events', __name__, template_folder='templates')

@events.route('/')
@login_required
def index():
    user_id = current_user.id

    # All events belonging to current user.
    # events = Event.query.filter_by(user_id=current_user.id)

    # All active events belonging to current user.
    events_active = Event.query.filter_by(user_id=user_id, status_id=100)
    events_active_count = events_active.count()

    # Events belonging to current user with status 400, completed.
    events_completed = Event.query.filter_by(user_id=user_id, status_id=400).all()

    return render_template('events/events.html',
                           events_active=events_active,
                           events_active_count=events_active_count,
                           events_completed=events_completed)


@events.route('/')
@login_required
def display_events():
    user_id = current_user.id

    # All events belonging to current user.
    # events = Event.query.filter_by(user_id=current_user.id)

    # All active events belonging to current user.
    events_active = Event.query.filter_by(user_id=user_id, status_id=100)
    events_active_count = events_active.count()

    # Events belonging to current user with status 400, completed.
    events_completed = Event.query.filter_by(user_id=user_id, status_id=400).all()

    return render_template("events/events.html",
                           events_active=events_active,
                           events_active_count=events_active_count,
                           events_completed=events_completed)


# Flask WTForms Create endpoint
@events.route('/create_event', methods=['GET', 'POST'])
@login_required
def create_event():
    form = NewEventForm(request.form)

    if request.method == 'POST' and form.validate():
        address = form.address.data
        address_line_two = form.address_line_two.data
        category_id = 100
        city = form.city.data
        country = form.country.data
        end_date = form.end_date.data
        last_edit_date = datetime.utcnow()
        name = form.name.data
        start_date = form.start_date.data
        state = form.state.data
        status_id = 100
        user_id = current_user.id
        zip_code = form.zip_code.data
        event = Event(address, address_line_two, category_id, city, country, end_date, last_edit_date, name,
                      start_date, state, status_id, user_id, zip_code)

        try:
            db.session.add(event)
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

        return redirect(url_for('events.display_events'))

    return render_template("events/create_event.html", form=form)


# JSON format endpoint
@events.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = NewEventForm(request.form)

    if request.method == 'POST' and form.validate():
        address = form.address.data
        address_line_two = form.address_line_two.data
        category_id = 100
        city = form.city.data
        country = form.country.data
        end_date = form.end_date.data
        last_edit_date = datetime.utcnow()
        name = form.name.data
        start_date = form.start_date.data
        state = form.state.data
        status_id = 100
        user_id = current_user.id
        zip_code = form.zip_code.data
        event = Event(address, address_line_two, category_id, city, country, end_date, last_edit_date, name,
                      start_date, state, status_id, user_id, zip_code)

        try:
            db.session.add(event)
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

        return redirect(url_for('events.display_events'))

    return render_template("events/create.html", form=form)


@events.route('/<event_id>', methods=['GET', 'POST'])
@login_required
def show(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()

    guests = event.guests

    return render_template("events/show.html", event=event, guests=guests)


@events.route('/update/<event_id>', methods=['GET', 'POST'])
@login_required
def update(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()

    form = UpdateEventForm()
    if request.method == "POST" and form.validate():
        event.address = form.address.data
        event.address_line_two = form.address_line_two.data
        event.city = form.city.data
        event.country = form.country.data
        event.end_date = form.end_date.data
        event.last_edit_date = datetime.utcnow()
        event.name = form.name.data
        event.start_date = form.start_date.data
        event.state = form.state.data
        event.zip_code = form.zip_code.data

        try:
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

        return redirect(url_for('events.show', event_id=event.id))
    elif request.method != "POST":
        form.address.data = event.address
        form.address_line_two.data = event.address_line_two
        form.city.data = event.city
        form.country.data = event.country
        form.end_date.data = event.end_date
        form.name.data = event.name
        form.start_date.data = event.start_date
        form.state.data = event.state
        form.zip_code.data = event.zip_code

    return render_template("events/update.html", event=event, form=form)


@events.route('/delete/<event_id>', methods=['GET', 'POST'])
@login_required
def delete(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()
    user_id = current_user.id
    if user_id == event.user_id:
        try:
            db.session.delete(event)
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

        return redirect(url_for('events.display_events'))

    return redirect(url_for('events.display_events'))

flaskproject/main/controllers.py
from flask import Blueprint, render_template, flash
from flask import current_app, redirect, request, url_for, json
from flask_security.decorators import roles_required
from flask_security import login_required, current_user
from flaskproject.main.forms.entry_forms import CreateEntryForm
from flaskproject.cache import cache
from flaskproject.data.models import Entry, db
from sqlalchemy import exc


main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
@login_required
def index():
    entries = [entry for entry in Entry.query.all()]
    current_app.logger.info('Displaying all entries.')

    return render_template('main.html', entries=entries)

@main.route('/entries/')
@login_required
@cache.cached(300)
def display_entries():
    entries = [entry for entry in Entry.query.all()]
    current_app.logger.info('Displaying all entries.')

    return render_template("entries.html", entries=entries)

@main.route('/entry/create', methods=['GET', 'POST'])
@login_required
def create_entry():
    form = CreateEntryForm(request.form)
    user_id = current_user.id

    if request.method == 'POST' and form.validate():
        title = form.title.data
        body = form.body.data
        user_id = user_id
        current_app.logger.info('Adding a new entry %s.', (title))
        entry = Entry(title, body, user_id)

        try:
            db.session.add(entry)
            db.session.commit()
            cache.clear()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

            return redirect(url_for('main.create_entry'))

        return redirect(url_for('main.display_entries'))

    return render_template("create_entry.html", form=form)

flaskproject/main/views.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
def index():
    return render_template('main/main.html')

flaskproject/users/views.py
from flask import Blueprint, render_template
from flask import request, redirect, url_for, json, current_app
from ..core import db
from flask_security import login_required, current_user
from datetime import datetime
from .forms import EditProfileForm
from .models import User
from sqlalchemy import exc

user = Blueprint('user', __name__, template_folder='templates')

@user.route('/')
@login_required
def index():
    return render_template('users/user_profile.html')

@user.route('/<user_id>', methods=['GET', 'POST'])
@login_required
def show(user_id):
    user_id = current_user.id
    user = User.query.filter_by(id=user_id).first_or_404()

    return render_template('users/user_profile.html', user=user)

@user.route('/edit', methods=['GET', 'POST'])
@login_required
def update():
    user_id = current_user.id
    user = User.query.filter_by(id=user_id).first_or_404()
    form = EditProfileForm()

    if request.method == "POST" and form.validate():
        user.email = form.email.data
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.last_edit_date = datetime.utcnow()

        try:
            db.session.commit()
        except exc.SQLAlchemyError as e:
            current_app.logger.error(e)

        return redirect(url_for('user.show', user_id=user.id))
    elif request.method != "POST":
        form.email.data = user.email
        form.last_name.data = user.last_name
        form.first_name.data = user.first_name

    return render_template('users/edit_profile.html', form=form)

flaskproject/templates/layouts/_datepicker_layout.html
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Flask Project</title>
    <meta name="description" content="Flask App">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include "assets/_datepicker_vendor_js.html" %}
    <link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
    {% include "assets/_datepicker_vendor_css.html" %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
    {% include "layouts/_menu.html" %}
    <div class="container">
      {% block container %}{% endblock %}
    </div>
    <footer class="footer"></footer>

    <script>
      $(document).ready(function(){
        $('.datepicker').datepicker({
          format: 'mm-dd-yyyy'
        });
      });
    </script>
  </body>
</html>

flaskproject/templates/layouts/_datetimepicker.html
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Flask Project</title>
    <meta name="description" content="Flask App">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include "assets/_datetimepicker_js.html" %}
    <link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
    {% include "assets/_datetimepicker_css.html" %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
    {% include "layouts/_menu.html" %}
    <div class="container">
      {% block container %}{% endblock %}
    </div>
    <footer class="footer"></footer>

    <script type="text/javascript">
      $(function () {
        $('.datetimepicker').datetimepicker({
          /*format: 'MM-DD-YYYY hh:mm:ss a'*/
          format: 'MM-DD-YYYY hh:mm'
        });
      });
    </script>
  </body>
</html>

flaskproject/templates/layouts/_login.html
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Flask Project - Login</title>
    <meta name="description" content="Flask App">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
    {% include "layouts/_menu.html" %}
    <div class="container">
      {% block container %}{% endblock %}
    </div>
    <footer class="footer"></footer>
  </body>
</html>

flaskproject/templates/layouts/_menu.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('home') }}">Flask App</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
          <li><a href="/main">Main</a></li>
          <li><a href="/events">Events</a></li>
          <li><a href="/entries">Entries</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.has_role('admin') %}
          <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
        {% endif %}
        {% if user.is_authenticated %}
          <li><a href="/user">User</a></li>
        {% endif %}
        {% if not user.is_authenticated %}
          <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span>Log In</a></li>
          <li><a href="/register"><span class="glyphicon glyphicon-log-in"></span>Register</a></li>
        {% else %}
          <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

flaskproject/templates/layouts/_register.html
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Flask Project - Registration</title>
    <meta name="description" content="Flask App">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include "assets/_datepicker_vendor_js.html" %}
    <link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
    {% include "assets/_datepicker_vendor_css.html" %}
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
  <nav class="navbar navbar-inverse">
    {% include "layouts/_menu.html" %}
  </nav>
  <div class="container">
    {% block container %}{% endblock %}
  </div>
  <footer class="footer"></footer>
  <script>
    $(document).ready(function(){

      $('.datepicker').datepicker({
        format: 'mm-dd-yyyy'
      });
    });
  </script>
  </body>
</html>

flaskproject/templates/layouts/_user_profile.html
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Flask Project - Edit Profile</title>
    <meta name="description" content="Flask App">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
    {% include "layouts/_menu.html" %}
    <div class="container">
      {% block container %}{% endblock %}
    </div>
    <footer class="footer"></footer>
  </body>
</html>

flaskproject/templates/layouts/boilerplate.html
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Flask Project</title>
    <meta name="description" content="Flask App">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
    {% include "layouts/_menu.html" %}
    <div class="container">
      {% block container %}{% endblock %}
    </div>
    <footer class="footer"></footer>
  </body>
</html>

flaskproject/templates/layouts/layout.html
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Flask Project</title>
    <meta name="description" content="Flask App">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>
  <body>
    {% include "layouts/_menu.html" %}
    <div class="container">
      {% block container %}{% endblock %}
    </div>
    <footer class="footer"></footer>
    
    <script type="text/javascript" src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
  </body>
</html>